language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: "zichd"
  password: "ELHHmtiF68PzhW7"
  server: https://test.pypi.org/legacy/
